# Generated by Django 4.1.7 on 2023-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('institucion', models.CharField(max_length=15)),
                ('hora_inscripcion', models.TimeField()),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO_ASISTEN', 'No Asisten')], default='RESERVADO', max_length=15)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
    ]
